<?php

namespace Nurikabe;
class GetSolvedTable {

    public function __construct($key)
    {
        $this->key = $key;
    }

    public function getSolvedTable(){
        return $this->solvedTables[$this->key];
    }

    public function getKey(){
        return $this->key;
    }

    private $key;
    private $solvedTables = [
        '3x3' => [
            [1,   CELL::SEA,   1],
            [CELL::SEA, CELL::SEA , CELL::SEA ],
            [2,   CELL::ISLAND , CELL::SEA ]
        ],
        '8x8easy' => [
            [CELL::SEA,CELL::SEA,2,CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA],
            [CELL::SEA,1,CELL::SEA,CELL::SEA,CELL::SEA,4,CELL::ISLAND,CELL::SEA],
            [CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND,2,CELL::SEA,CELL::ISLAND,CELL::SEA],
            [CELL::SEA,2,CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND,CELL::SEA],
            [4,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND,2,CELL::SEA,CELL::SEA],
            [CELL::ISLAND,CELL::SEA,CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND],
            [CELL::ISLAND,CELL::SEA,CELL::ISLAND,3,CELL::SEA,CELL::ISLAND,CELL::SEA,3],
            [CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND,3,CELL::SEA,CELL::ISLAND]
        ],
        '8x8med' => [
            [CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA],
            [2,CELL::SEA,CELL::ISLAND,CELL::ISLAND,CELL::SEA,CELL::ISLAND,CELL::ISLAND,CELL::ISLAND],
            [CELL::SEA,4,CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND],
            [CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,2,CELL::ISLAND,CELL::SEA,6],
            [CELL::SEA,CELL::ISLAND,CELL::SEA,2,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND],
            [CELL::SEA,2,CELL::SEA,CELL::ISLAND,CELL::SEA,CELL::ISLAND,CELL::SEA,CELL::SEA],
            [5,CELL::SEA,CELL::SEA,CELL::SEA,4,CELL::ISLAND,CELL::ISLAND,CELL::SEA],
            [CELL::ISLAND,CELL::ISLAND,CELL::ISLAND,CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA]
        ],
        '10x10' => [
            [4,CELL::ISLAND,CELL::ISLAND,CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,1],
            [CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND,CELL::ISLAND,CELL::SEA,CELL::ISLAND,CELL::SEA],
            [CELL::SEA,CELL::ISLAND,CELL::SEA,CELL::ISLAND,CELL::ISLAND,CELL::SEA,3,CELL::SEA,3,CELL::SEA],
            [CELL::SEA,2,CELL::SEA,3,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND,CELL::SEA],
            [1,CELL::SEA,CELL::SEA,CELL::SEA,4,CELL::ISLAND,CELL::SEA,3,CELL::SEA,CELL::SEA],
            [CELL::SEA,CELL::SEA,2,CELL::ISLAND,CELL::SEA,CELL::ISLAND,CELL::SEA,CELL::ISLAND,CELL::SEA,5],
            [CELL::SEA,CELL::ISLAND,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND,CELL::SEA,CELL::ISLAND,CELL::SEA,CELL::ISLAND],
            [CELL::SEA,CELL::ISLAND,CELL::SEA,1,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND],
            [CELL::SEA,CELL::ISLAND,4,CELL::SEA,CELL::SEA,3,CELL::ISLAND,CELL::ISLAND,CELL::SEA,CELL::ISLAND],
            [CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND,2,CELL::SEA,CELL::SEA,CELL::SEA,CELL::SEA,CELL::ISLAND]
        ]
    ];
}